spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce  # MongoDB connection URI
      database: ecommerce  # Database name
  application:
    name: ecommerce-invoice-service  # Application name
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false  # Prevents serialization errors for empty beans

server:
  port: 8080  # Server port

logging:
  level:
    root: INFO  # Set logging level
    com.example.ecommerce: DEBUG  # Set logging level for your application package

# Optional: Configure CORS if needed
# cors:
#   allowed-origins: "*"
#   allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"