spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&jdbcCompliantTruncation=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 9094

SECRET: c36ac04b56bf4a7186952542911e2f2ce49934053fb1551f